export const team = [
  {
    id: 1,
    image: "../Board/Aldi-Agaj.png",
    title: "CEO | FOUNDER",
    subtitle: "CHAIR OF BOARD OF DIRECTORS",
    name: "Dr, Aldi Agaj, JD, LLM",
    linkedln: "https://www.linkedin.com/in/aldi-agaj-7167b182/",
  },
  {
    id: 2,
    image: "../Board/Carlos-Colman.png",
    title: "CTO | FOUNDER",
    subtitle: "BOARD OF DIRECTORS",
    name: "Dr, Carlos Meixner, PhD",
    linkedln: "https://www.linkedin.com/in/carlos-colman-meixner-b1a8959/",
  },
  {
    id: 3,
    image: "../Board/Kristen-Robertson.png",
    title: "ART DIRECTOR",
    subtitle: "BOARD OF DIRECTORS",
    name: "Kristen Robertson",
    linkedln: "https://www.linkedin.com/in/kristenrobertson85/",
  },
  {
    id: 4,
    image: "../Board/Edward-Bennett.png",
    title: "XR DIRECTOR",
    subtitle: "BOARD OF DIRECTORS",
    name: "Edward Bennett",
    linkedln: "https://www.linkedin.com/in/edward-bennett-3354654/",
  },
  {
    id: 5,
    image: "../Board/Juan-Carlos.png",
    title: "RESEARCH AND SCIENCE COORDINATOR",
    subtitle: "",
    name: "Dr, Juan Carlos Ruiz, PhD",
    linkedln: "https://www.linkedin.com/in/jcruiz-guajardo/",
  },
  {
    id: 6,
    image: "../Team-members/Chinamay-Kasareddy.png",
    title: "LEAD UNITY DEVELOPER | XR ENGINEER",
    subtitle: "",
    name: "Chinamay Kasarendy",
  },
  {
    id: 7,
    image: "../Team-members/Mathieu-Cardinal.png",
    title: "LEAD VR DEVELOPER",
    subtitle: "",
    name: "Mathieu Cardinal",
  },
  {
    id: 8,
    image: "../Team-members/Ryan-Villanueva.png",
    title: "LEAD PRODUCT DESIGNER",
    subtitle: "",
    name: "Ryan Villanueva",
  },
  {
    id: 9,
    image: "../Team-members/Ivan-Monges.png",
    title: "GAME DEVELOPER | UNITY DEVELOPER",
    subtitle: "",
    name: "Ivan Monges",
  },
  {
    id: 10,
    image: "../Team-members/Ines-Chokri.png",
    title: "VR DEVELOPER | UNITY DEVELOPER",
    subtitle: "",
    name: "Ines Chokri",
  },
  {
    id: 11,
    image: "../Team-members/Vineet-Nalawade.png",
    title: "XR DEVELOPER",
    subtitle: "",
    name: "Vineet Nalawade",
  },
  {
    id: 12,
    image: "../Team-members/Jesse-Fischbeck.png",
    title: "UNITY | VR DEVELOPER〡DESIGNER GENERALIST",
    subtitle: "",
    name: "Jesse Fischbeck",
  },
  {
    id: 13,
    image: "../Team-members/Gurmehar-Dev.png",
    title: "VR DEVELOPER | DESIGNER GENERALIST",
    subtitle: "",
    name: "Gurmehar Dev",
  },
  {
    id: 14,
    image: "../Team-members/Utsav-Chaudhary.png",
    title: "VR DEVELOPER",
    subtitle: "",
    name: "Utsav Chaudhary",
  },
  {
    id: 15,
    image: "../Team-members/Colin-Jackson.png",
    title: "GAME DEVELOPER | GAME DESIGNER",
    subtitle: "",
    name: "Colin Jackson",
    linkedln: "https://www.linkedin.com/in/colijackson/",
  },
  {
    id: 16,
    image: "../Team-members/Adhiraj.png",
    title: "UNITY | UNREAL ENGINE | GAME DEVELOPER",
    subtitle: "",
    name: "Adhiraj Bhagawati",
  },
  {
    id: 17,
    image: "../Team-members/Rohit-Ramesh.png",
    title: "UNITY DEVELOPER",
    subtitle: "",
    name: "Rohit Ramesh",
  },
  {
    id: 18,
    image: "../Team-members/Fiori-Bejleri.png",
    title: "VR DEVELOPER | 3D GENERALIST",
    subtitle: "",
    name: "Fiori Bejleri",
  },
  {
    id: 19,
    image: "../Team-members/Mohosoa-Sello.png",
    title: "VR DEVELOPER | AR DESIGNER",
    subtitle: "",
    name: "Mohasoa Sello",
  },
  {
    id: 20,
    image: "../Team-members/Eli-Miller.png",
    title: "GAME DESIGNER | GAME DEVELOPER",
    subtitle: "",
    name: "Eli Miller",
  },
  {
    id: 21,
    image: "../Team-members/Sanchit-Keni.png",
    title: "GAME DESIGNER | PROGRAMMER",
    subtitle: "",
    name: "Sanchit S. Keni",
  },
  {
    id: 22,
    image: "../Team-members/William-Chilcote.png",
    title: "BACK-END AND MULTIPLAYER DEVELOPER",
    subtitle: "",
    name: "William Chilcotei",
  },
  {
    id: 23,
    image: "../Team-members/Kelly-Lallemand.png",
    title: "GAME DESIGN",
    subtitle: "",
    name: "Kelly Lallemand",
  },
  {
    id: 24,
    image: "../Team-members/Emma-Turnbull.png",
    title: "VOICE TEACHER | ARTIST",
    subtitle: "",
    name: "Emma Turnbull",
  },
  {
    id: 25,
    image: "../Team-members/Camilla-Grassotto.png",
    title: "3D GENERALIST",
    subtitle: "",
    name: "Camilla Grassotto",
  },
  {
    id: 26,
    image: "../Team-members/JC-Mariscal.png",
    title: "3D ARTIST | DESIGNER",
    subtitle: "",
    name: "JC Mariscal",
  },
  {
    id: 27,
    image: "../Team-members/Roberta-Di-Gioia.png",
    title: "3D ARTIST | 2D ARTIST",
    subtitle: "",
    name: "Roberta Di Gioia",
  },
  {
    id: 28,
    image: "../Team-members/Phodchara-phumala.png",
    title: "2D ARTIST",
    subtitle: "",
    name: "Phodchara Phumala (Norman)",
  },
  {
    id: 29,
    image: "../Team-members/Iasmin-Prati.png",
    title: "2D ARTIST",
    subtitle: "",
    name: "Iasmin Prati",
  },
  {
    id: 30,
    image: "../Team-members/Aws-Alali.png",
    title: "FRONT-END DEVELOPER",
    subtitle: "",
    name: "Aws Alali",
  },
  {
    id: 31,
    image: "../Team-members/Abdulrohman-Alakrad.png",
    title: "FRONT-END DEVELOPER",
    subtitle: "",
    name: "Abdulrohman Alakrad",
  },
  {
    id: 32,
    image: "../Team-members/Salihullah-Salarzai.png",
    title: "FULLSTACK DEVELOPER",
    subtitle: "",
    name: "Salihullah Salarzai",
    linkedln: "https://www.linkedin.com/in/salihullah-salarzai-86b82616b/",
  },
  {
    id: 33,
    image: "../Team-members/Kimberly-Liang.png",
    title: "GRAPHIC DESIGNER",
    subtitle: "",
    name: "Kimberly Liang",
  },
  {
    id: 34,
    image: "../Team-members/Evita-Lobo.png",
    title: "PRODUCT DESIGNER",
    subtitle: "",
    name: "Evita Lobo",
  },
  {
    id: 35,
    image: "../Team-members/Fasiha-Iqbal.png",
    title: "UX | UI WEB DESIGNER",
    subtitle: "",
    name: "Fasiha Iqbal",
  },
  {
    id: 36,
    image: "../Team-members/Marialuisa-Yazar.png",
    title: "UX | UI DESIGNER",
    subtitle: "",
    name: "Marialuisa Yazar",
  },
  {
    id: 37,
    image: "../Team-members/Sam-Muktan.png",
    title: "UX | UI DESIGNER",
    subtitle: "",
    name: "Sam Muktan",
  },
  {
    id: 38,
    image: "../Team-members/Fiorenza-Ferrara.png",
    title: "SOCIAL MEDIA MARKETING",
    subtitle: "",
    name: "Fiorenza Ferrara",
  },
  {
    id: 39,
    image: "../Team-members/Videm-Youri-Owiro.png",
    title: "MARKET STRATEGY CONSULTANT",
    subtitle: "",
    name: "Videm Youri-Owiro",
  },
  {
    id: 40,
    image: "../Team-members/Zubair-Ahmad.png",
    title: "SEO AND WORDPRESS EXPERT",
    subtitle: "",
    name: "Zubair Ahmad",
  },
  {
    id: 41,
    image: "../Team-members/Mike-Smithwick.png",
    title: "SENIOR IOS AND MAC DEVELOPER",
    subtitle: "",
    name: "Mike Smithwick",
  },
  {
    id: 42,
    image: "../Team-members/Lucia-Roman-Canivell.png",
    title: "VIDEO EDITOR AND DESIGNER",
    subtitle: "",
    name: "Lucia Roman Canivell",
  },
  {
    id: 43,
    image: "../Team-members/Mingwei-Zhang.png",
    title: "GAME DEVELOPER",
    subtitle: "",
    name: "Mingwei Zhang",
  },
  {
    id: 44,
    image: "../Team-members/Jeff-Yarbrough.png",
    title: "3D ENVIRONMENT ARTIST",
    subtitle: "",
    name: "Jeff Yarbrough",
  },
  {
    id: 45,
    image: "../Team-members/Francesco-Principe.png",
    title: "GAME DESIGNER AND DEVELOPER",
    subtitle: "",
    name: "Francesco Principe",
    linkedln: "https://www.linkedin.com/in/francesco-principe/",
  },
  {
    id: 46,
    image: "../Team-members/Alexandra.png",
    title: "GAME DESIGNER",
    subtitle: "",
    name: "Alexandra Kaminska",
  },
  {
    id: 47,
    image: "../Team-members/Anne-Marie.png",
    title: "GAME DESIGNER",
    subtitle: "",
    name: "Anne-Marie Schleiner",
  },
  {
    id: 48,
    image: "../Team-members/Ben-Geer.png",
    title: "3D ARTIST",
    subtitle: "",
    name: "Ben Geer",
  },
  {
    id: 49,
    image: "../Team-members/Ehsan-Akhlaghi.png",
    title: "XR DEVELOPER",
    subtitle: "",
    name: "Ehsan Akhlaghi",
  },
  {
    id: 50,
    image: "../Team-members/Gaia-DAgnelli.png",
    title: "SOCIAL MEDIA MARKETING",
    subtitle: "",
    name: "Gaia D'Agnelli",
  },
  {
    id: 51,
    image: "../Team-members/Ensar.png",
    title: "FULLSTACK DEVELOPER",
    subtitle: "",
    name: "Ensar Dedeoglu",
    linkedln: "https://www.linkedin.com/in/ensar-dedeoglu",
  },
  {
    id: 52,
    image: "../Team-members/Daniel-Meyer.png",
    title: "LEAD PROGRAMMER",
    subtitle: "",
    name: "Daniel Meyer",
    linkedln: "https://www.linkedin.com/in/daniel-meyer-401a8b172/",
  },
  {
    id: 54,
    image: "../Team-members/Emmanuel-Galdamez.png",
    title: "PROGRAMMER",
    subtitle: "",
    name: "Emmanuel Galdamez",
    linkedln: "",
  },
  {
    id: 55,
    image: "../Team-members/Jesse-Estrada.png",
    title: "UNITY DEVELOPER",
    subtitle: "",
    name: "Jesse Estrada",
    linkedln: "https://www.linkedin.com/in/jaestrada97/",
  },
  {
    id: 56,
    image: "../Team-members/Noelle-Tagupa.png",
    title: "WEB DESIGNER",
    subtitle: "",
    name: "Noelle Tagupa",
    linkedln: "https://www.linkedin.com/in/nmtagupa/",
  },
  {
    id: 57,
    image: "../Team-members/Rachel-Clarke.png",
    title: "3D VISUAL ARTIST",
    subtitle: "",
    name: "Rachel Clarke",
    linkedln: "",
  },
  {
    id: 58,
    image: "../Team-members/Ronald-Goennier.png",
    title: "PROGRAMMER",
    subtitle: "",
    name: "Ronald Goennier",
    linkedln: "https://www.linkedin.com/in/ronald-g-ab717499/",
  },
  {
    id: 59,
    image: "../Team-members/Ashutosh-Nandanwar.png",
    title: "3D ENVIRONMENT ARTIST",
    subtitle: "",
    name: "Ashutosh Nandanwar",
    linkedln: "https://www.linkedin.com/in/ashutosh-nandanwar/",
  },
  {
    id: 60,
    image: "../Team-members/Roberto-Buonomo.png",
    title: "MARINE BIOLOGY CONSULTANT",
    subtitle: "",
    name: "Roberto Buonomo",
    linkedln: "https://www.linkedin.com/in/roberto-buonomo-10956380/",
  },
  {
    id: 61,
    image: "../Team-members/Mirco-Buonomo.png",
    title: "SOUND ENGINEER | SOUND ART DIRECTOR",
    subtitle: "",
    name: "Mirco Buonomo",
    linkedln: "https://www.linkedin.com/in/mircobuonomo/",
  },
  {
    id: 62,
    image: "../Team-members/Gilbert-Gallo.png",
    title: "GAME DESIGNER",
    subtitle: "",
    name: "Gilbert Gallo",
    linkedln: "https://www.linkedin.com/in/gilbertgallocreative/",
  },
  {
    id: 63,
    image: "../Team-members/Anshika-Gupta.png",
    title: "VR DEVELOPER",
    subtitle: "",
    name: "Anshika Gupta",
    linkedln: "https://www.linkedin.com/in/anshika-gupta-ab1324193/",
  },
  {
    id: 64,
    image: "../Team-members/Kanad-Dongre.png",
    title: "MUSIC PRODUCER | COMPOSER | SOUND DESIGNER",
    subtitle: "",
    name: "Anshika Gupta",
    linkedln: "https://www.linkedin.com/in/kanad-dongre-12693221b/",
  },
];
